[workspace]
members  = ["geolite-core", "geolite-sqlite", "geolite-diesel"]
resolver = "2"

[workspace.package]
rust-version = "1.75"

[profile.release]
opt-level = "z"
lto       = true
strip     = true
