[workspace]
members  = ["geolite-core", "geolite-sqlite", "geolite-diesel", "xtask"]
resolver = "2"

[workspace.package]
rust-version = "1.86"

[workspace.dependencies]
geo = { version = "0.32", default-features = false }
libsqlite3-sys = { version = ">=0.17.2, <0.36.0" }

[profile.release]
opt-level = "z"
lto       = true
strip     = true
